unstable_features = true
version = "Two"
tab_spaces = 2
hard_tabs = true
indent_style = "Block"
merge_derives = true
max_width = 120
newline_style = "Unix"
edition = "2021"
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_try_shorthand = true
wrap_comments = true
skip_children = false
format_macro_matchers = true
match_arm_blocks = true
match_arm_leading_pipes = "Preserve"
use_small_heuristics = "Max"
use_field_init_shorthand = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
